import Link from "next/link";
import { ArrowRight, Building2, ShieldCheck, Sofa } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

export default function SobrePage() {
  return (
    <main><section className="border-b border-border bg-muted/40"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-24"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-gold">Silva Móveis</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">Uma loja feita para apresentar bons móveis.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground">Esta página receberá o conteúdo institucional oficial da empresa.</p></div></section><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-24"><div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="p-6"><Sofa className="size-7 text-gold" /><h2 className="mt-5 font-semibold">Catálogo</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Produtos cadastrados e gerenciados pela loja.</p></CardContent></Card><Card><CardContent className="p-6"><Building2 className="size-7 text-gold" /><h2 className="mt-5 font-semibold">Operação</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Informações da empresa serão publicadas aqui.</p></CardContent></Card><Card><CardContent className="p-6"><ShieldCheck className="size-7 text-gold" /><h2 className="mt-5 font-semibold">Compra</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Checkout e atendimento serão conectados ao backend.</p></CardContent></Card></div><div className="mt-12 rounded-md border border-border bg-graphite p-8 text-white sm:p-12"><h2 className="text-3xl font-semibold">Conheça o catálogo</h2><p className="mt-3 max-w-xl text-white/70">Veja os produtos disponíveis e acompanhe a evolução da loja.</p><Link href="/catalogo" className="mt-7 inline-flex h-9 items-center gap-1.5 rounded-lg bg-gold px-2.5 text-sm font-medium text-graphite transition hover:bg-gold/90">Ver catálogo<ArrowRight className="size-4" /></Link></div></section></main>
  );
}
